FROM node:22-alpine

WORKDIR /app

# On installe les dépendances en premier (optimisation du cache Docker)
COPY package*.json ./
RUN npm install

# On expose le port par défaut de Vite
EXPOSE 5173

# On lance le serveur de dev avec l'option --host pour accepter les connexions externes
CMD ["npm", "run", "dev", "--", "--host"]